### ISSUE TITLE
Cant test the sample on web

### ISSUE THREAD

**Issue by Macacoazul01** [joseph-grabinger/flutter_to_pdf#48]
Not sure if this is related to the other issue on android, but on web nothing happens after i press any of the buttons.

It seems like the function to generate the pdf is running on the background (because the mouse stucks on the hand pointer for some time) but the file isnt created.

![image](https://github.com/dunef-com/flutter_to_pdf/assets/57464965/74d84ee2-3780-4f83-96ce-86dffc4a5c6e)

**Comment by Macacoazul01** [comment]
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.16.4, on Microsoft Windows [versao 10.0.22631.2861], locale pt-BR)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
[√] Chrome - develop for the web
[X] Visual Studio - develop Windows apps
    X Visual Studio not installed; this is necessary to develop Windows apps.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components
[√] Android Studio (version 2022.3)
[√] VS Code (version 1.85.1)
[√] Connected device (4 available)
[√] Network resources

! Doctor found issues in 1 category.

**Comment by joseph-grabinger** [comment]
This is a known issue on Web. Walking the widget tree and generating the PDF takes forever on web for some reason. It should finish at some point though.
