### ISSUE TITLE
Question about the license for this package

### ISSUE THREAD

**Issue by andrelrf1** [joseph-grabinger/flutter_to_pdf#57]
This is not a bug, it's just a question due to the discrepancy between the package's license type. Is this package MIT or does it have a different license? Because here on github it says one thing and on pub.dev it says another.

**Comment by joseph-grabinger** [comment]
The package is licensed under MIT. It previously fell under a different license before the repo was transferred. 

The license on pub.dev will also be MIT as soon as I find time to push a new update to pub.dev :)

**Comment by rydmike** [comment]
Maybe not super urgent, but it would be nice if you could publish an update with the revised MIT license on pub too. If you use the package now and use Flutter's standard license display page, e.g. via the convenient `showAboutDialog` to nicely show all licenses used by your app, as required by some/many of the license types, you now get the none MIT version that is included with the package.

I just discovered this package and am looking forward to trying it out to see what it can do. Can't tell you how long I have been looking for for something that can do this.

I will probably need the custom font support to really be able to use it, but going to try it out as it iss to start with.

**Comment by joseph-grabinger** [comment]
Package is now updated on [pub.dev](https://pub.dev/packages/flutter_to_pdf).

Will close this issue. Feel free to reopen if there are any further questions :)

**Comment by joseph-grabinger** [comment]
Package is now updated on [pub.dev](https://pub.dev/packages/flutter_to_pdf).

Will close this issue. Feel free to reopen if there are any further questions :)
