### ISSUE TITLE
Unsupported Font: lato

### ISSUE THREAD

**Issue by jhoncke2** [joseph-grabinger/flutter_to_pdf#80]
I am converting a widget in to pdf with the function ExportDelegate.exportToPdfDocument(frameId). But, the method throws the error Unsupported Font: lato. Lato is a font that i added from google fonts to the project in pubspec.yalm. And, i am using this font into the widget that i am converting to pdf. Please, help me.

This is the stacktrace:

I/flutter ( 4678): Exception: Unsupported Font: lato
I/flutter ( 4678): #0      TextStyleConverter.resolveFont (package:flutter_to_pdf/args/text_style.dart:61:9)
I/flutter ( 4678): #1      TextStyleConverter.toPdfTextStyle (package:flutter_to_pdf/args/text_style.dart:36:36)
I/flutter ( 4678): #2      TextConverter.toPdfWidget (package:flutter_to_pdf/widgets/text.dart:21:23)
I/flutter ( 4678): #3      ExportInstance.matchWidget (package:flutter_to_pdf/export_instance.dart:173:34)
I/flutter ( 4678): #4      ExportInstance._visit (package:flutter_to_pdf/export_instance.dart:55:29)
I/flutter ( 4678): <asynchronous suspension>
I/flutter ( 4678): #5      ExportInstance.matchWidget (package:flutter_to_pdf/export_instance.dart:226:48)
I/flutter ( 4678): <asynchronous suspension>
I/flutter ( 4678): #6      ExportInstance._visit (package:flutter_to_pdf/export_instance.dart:55:23)
I/flutter ( 4678): <asynchronous suspension>
I/flutter ( 4678): #7      ExportInstance.matchWidget (package:flutter_to_pdf/export_instance.dart:84:31)
I/flutter ( 4678): <asynchronous suspension>
I/flutter ( 4678): #8      ExportInstance._visit (package:flutter_to_pdf/export_instance.dart:55:23)
I/flutter ( 4678): <asynchronous suspension>
I/flutter ( 4678): #9      ExportInstance.matchWidget (package:flutter_to_pdf/export_instance.dart:150:31)
I/flutter ( 4678): <asynchronous suspension>
I/flutter ( 4678): #10

**Comment by joseph-grabinger** [comment]
Are you using the [google_fonts](https://pub.dev/packages/google_fonts) package? 

Or are you using a custom Lato font which you added as a font asset to the projects `pubspec.yml` ?

**Comment by jhoncke2** [comment]
I added it as a font asset to the projects pybspec.yaml

**Comment by joseph-grabinger** [comment]
Did you register the font (in this case `lato`) when instantiating the `ExportDelegate` like the following? 

```dart
final ExportDelegate myExportDelegate = ExportDelegate(
    ttfFonts: {
      'lato': 'assets/fonts/Lato-Regular.ttf', // Path can differ but should point to the correct location of the ttf-file
    },
  );
```
Furthermore, you must then use the **same** `ExportDelegate` to export the frame containing the fonts. 

```dart
final pdf = await myExportDelegate.exportToPdfDocument('someFrameID');
```

**Comment by jhoncke2** [comment]
Thank you for the help.
Which version of the flutterToPdf package do i have to use? I have in my
pubspec.yaml the version 0.1.1 and the constructor of ExportDelegate has
just the parameter "options" which type is ExportOptions.

**Comment by jhoncke2** [comment]
I have solved the problem by updating the package version to 0.2.0 and
applying your solution. Thank you so much.
